### ISSUE TITLE
error running cli

### ISSUE THREAD

**Issue by bigmule** [tabone/jsonapi2raml#15]
jsonapi2raml AirBookRQ.json AirBookRQ.raml
Got the following error:

/usr/local/lib/node_modules/jsonapi2raml/src/index.js:70
    return Promise.all(info.resources.map(parseResource)).then(() => {
                                      ^

TypeError: info.resources.map is not a function
    at Object.generate (/usr/local/lib/node_modules/jsonapi2raml/src/index.js:70:39)
    at fs.readFile (/usr/local/lib/node_modules/jsonapi2raml/cli/index.js:46:16)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)

**Comment by bigmule** [comment]
[songs.json.txt](https://github.com/tabone/jsonapi2raml/files/1907790/songs.json.txt)
this is the input file

**Comment by tabone** [comment]
I'm assuming that `song.json.txt` is the payload file you're providing to jsonapi2raml. If that's the case, make sure that it follows the [payload spec](https://github.com/tabone/jsonapi2raml#payload-structure).

Can you update the input file, retry and get back to me?

**Comment by bigmule** [comment]
Hi Luca,
The payload 'song.json.txt" was not compliant to the "payload spec". 
I'm closing this issue.
Regards,
Juan
